### ISSUE TITLE
Online demo not working

### ISSUE THREAD

**Issue by reincore** [levelopers/Ecommerce-Reactjs#1]
The online demo link does not seem to work, instead the user sees below message:

![image](https://user-images.githubusercontent.com/6319768/67851198-f6cf1a00-fb1a-11e9-8117-836bc1ce6807.png)

**Comment by levelopers** [comment]
sorry for the inconvenience, i deploy both frontend and backend on heroku, it seems running out of free dyno hours quota since lots of visitors to the web app
