### ISSUE TITLE
Server not working

### ISSUE THREAD

**Issue by Sonny1314** [levelopers/Ecommerce-Reactjs#3]
I tried changing the links of images from seed/index.js file in the node server, but the output is still the same at localhost:3000/products.
How do I change that??
![image](https://user-images.githubusercontent.com/50945527/84173351-cbda7a80-aa9a-11ea-9c6a-d02c59a7580f.png)

![image](https://user-images.githubusercontent.com/50945527/84173291-b5ccba00-aa9a-11ea-9b11-48aaee962672.png)

Could you help me with this? And I am also confused how are images loading even without the server???

**Comment by levelopers** [comment]
i fixed the issue, you can fill up ./configs/mongo-config.js file with your mongo url, it should work by now.
sorry about the inconvenience
